spring:
  application:
    name: 4iren-processing

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://s4.java21.net:13306/aiot03_team4
    username: aiot03_team4
    password: Yky2!)i0b-h6kYwZ
    type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 15
        acknowledge-mode: auto
    template:
      exchange: ${RABBIT_EXCHANGE_NAME}
      routing-key: ${RABBIT_ROUTING_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

influx:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}

sensor-context:
  base-url: http://localhost:8081